# .readthedocs.yaml

python_version: 3.8

# 指定依赖文件路径
requirements_file: requirements.txt

# 项目基本信息
name: Python & 图像处理教程
repo_url: https://github.com/Aloha0604/teach.git

# 配置 Sphinx 主题和选项
sphinx:
  theme: sphinx_rtd_theme

# 指定操作系统环境，适用于构建平台
os: windows  # 可以改为 'windows' 或其他支持的平台名称

# 添加环境变量配置，如果有必要
envs:
  - name: PYTHONPATH
    value: ./src
