# .readthedocs.yaml

version: 2

# 设置操作系统、Python 版本以及其他工具
build:
  os: ubuntu-22.04  # 指定构建平台
  tools:
    python: "3.10"   # Python 版本

# 使用 Sphinx 构建文档
sphinx:
  builder: html
  configuration: source/conf.py

# 可选：生成其他格式的文档（PDF、ePub）
# formats:
#   - pdf
#   # - epub

# 安装构建所需的依赖包
# python:
#   install:
#     - requirements: docs/requirements.txt

